import "@/app/globals.css";
import type { Metadata } from "next";
import { Footer } from "@/utils/ui/layout/Footer";
import { Header } from "@/utils/ui/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="relative mx-auto flex min-h-screen w-auto max-w-2xl flex-col shadow-lg">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
